### ISSUE TITLE
Создать площадку для тестирования

### ISSUE THREAD

**Issue by dzantiev** [odvapro/element#261]
- на DevO2 создать площадку element.dev.odva.pro
- настроить выкат через gihub actions ветки develop (https://github.com/odvapro/bitrixCI/blob/main/.github/workflows/main.yml тут я писал action для битрикса - нужно подобное написать)
- протестить и выкатить все задачи на тесте туда

**Comment by sg-mon** [comment]
https://github.com/odvapro/element/pull/263
