### ISSUE TITLE
ошибки в поле text

### ISSUE THREAD

**Issue by sg-mon** [odvapro/element#268]
при загрузке картинки:
![image](https://user-images.githubusercontent.com/53168718/109150272-b4066c00-7779-11eb-9c75-3a25fa34c9cc.png)
![image](https://user-images.githubusercontent.com/53168718/109150311-c08ac480-7779-11eb-8e7c-b1cbcaf7e525.png)

**Comment by dzantiev** [comment]
Сейчас на странице списка выводиться одно содержимое а на детальной другое
